- hosts: all
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: installing httpd
      action: yum pkg=httpd state=present
      when: inventory_hostname in groups['dev']

    - name: stg server
      action: yum pkg=httpd state=present
      when: inventory_hostname in groups['stg'] 
